spring.application.name=OnlineMarket
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineMarket
spring.datasource.username=postgres
spring.datasource.password=5922
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true